
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

db.url = jdbc:postgresql://localhost:5432/academia
db.username = app_pruebaconjdbc
db.password = 12345
